linters:
  disable-all: false
  enable:
  - bidichk
  - copyloopvar
  - decorder
  - dogsled
  - dupl
  - dupword
  - errcheck
  - errname
  - errorlint
  - exportloopref
  - gci
  - goconst
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - importas
  - ineffassign
  - intrange
  - lll
  - mirror
  - misspell
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - nlreturn
  - predeclared
  - reassign
  - revive
  - sloglint
  - staticcheck
  - tagalign
  - tagliatelle
  - testifylint
  - whitespace
  - wrapcheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace